version: '3.4'

services:
  wunderidentityprovider:
    image: ghcr.io/tanmoysg/wunder-identity-provider:latest
    ports:
      - 5000:5000
    volumes:
      - ${PWD}/configs/server-config.json:/app/configs/server-config.json